set(OS_Detected FALSE)
if (WIN32)
    set(OS_WINDOWS TRUE)
    set(OS_Detected TRUE)
    add_compile_definitions(OS_WINDOWS)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(OS_MACOS TRUE)
    set(OS_Detected TRUE)
    add_compile_definitions(OS_MACOS)
elseif(UNIX AND NOT APPLE)
    set(OS_LINUX TRUE)
    set(OS_Detected TRUE)
    add_compile_definitions(OS_LINUX)
endif()