if (WIN32)
    SET(OS_WINDOWS TRUE)
    add_compile_definitions(OS_WINDOWS)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    SET(OS_MACOS TRUE)
    add_compile_definitions(OS_MACOS)
elseif(UNIX AND NOT APPLE)
    SET(OS_LINUX TRUE)
    add_compile_definitions(OS_LINUX)
else()
    message(FATAL_ERROR "Unsupported OS")
endif()