name: Build PSP platform

on:
  push:
    branches: [ master, platform_psp ]
    paths:
      - 'core/**'
      - 'platform-psp/**'
  pull_request:
    branches: [ master ]

jobs:
  build-psp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run build in pspdev container
        uses: docker://kremi151/pspdev:latest
        with:
          entrypoint: ./.github/workflows/scripts/build-in-docker.sh
          args: platform-psp
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: FunkyBoy-PSP
          path: "${{ github.workspace }}/platform-psp/cmake-build/EBOOT.PBP"
