name: Build SDL platform

on:
  push:
    # Temporary as long as I'm working on this branch
    # TODO: Just before creating a PR, put master here
    branches: [ graphics ]
  pull_request:
    branches: [ master ]

jobs:
  build-sdl:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
                cmakeMode: CMakeListsTxtBasic
                cmakeArgs: ''
              - os: macos-latest
                generator: Ninja
                cmakeMode: CMakeListsTxtBasic
                cmakeArgs: ''
              - os: windows-latest
                generator: VS16Win64
                cmakeMode: CMakeListsTxtAdvanced
                cmakeArgs: -DSDL2_DIR="${{ github.workspace }}\sdl2\SDL2-2.0.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies (Ubuntu)
        if: ${{ startsWith(matrix.config.os, 'ubuntu-') }}
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Install dependencies (macOS)
        if: ${{ startsWith(matrix.config.os, 'macos-') }}
        run: brew install sdl2
      - name: Install dependencies (Windows)
        if: ${{ startsWith(matrix.config.os, 'windows-') }}
        run: |
          Invoke-WebRequest 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip' -OutFile "${{ github.workspace }}\sdl2.zip"
          expand-archive -path "${{ github.workspace }}\sdl2.zip" -destinationpath "${{ github.workspace }}\sdl2"
        shell: powershell
      - name: Build with CMake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          cmakeGenerator: ${{ matrix.config.generator }}
          cmakeListsOrSettingsJson: ${{ matrix.config.cmakeMode }}
          cmakeAppendedArgs: ${{ matrix.config.cmakeArgs }}
