name: Build 3DS platform

on:
  push:
    branches: [ master, platform_3ds_poc ]
  pull_request:
    branches: [ master ]

jobs:
  build-3ds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run build in DevkitARM container
        uses: docker://devkitpro/devkitarm:20200730
        with:
          entrypoint: cd /github/workspace/platform-3ds && mkdir cmake-build-3ds && cd cmake-build-3ds && cmake .. && make
