name: Build SDL platform

on:
  push:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'platform-sdl/**'
      - '.github/workflows/build-sdl.yml'
      - '.github/workflows/scripts/pack-macos-sdl.sh'
  pull_request:
    branches: [ master ]

jobs:
  build-sdl-unix:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                artifact: FunkyBoy-linux
              - os: macos-latest
                artifact: FunkyBoy-macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies (Ubuntu)
        if: ${{ startsWith(matrix.config.os, 'ubuntu-') }}
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libgtk-3-dev libx11-dev
      - name: Install dependencies (macOS)
        if: ${{ startsWith(matrix.config.os, 'macos-') }}
        run: brew install sdl2
      - name: Build with CMake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          buildDirectory: "${{ github.workspace }}/platform-sdl/cmake-build"
          cmakeBuildType: Release
      - name: Copy SDL2 library
        run: cp $(cmake ./platform-sdl/ -L | grep SDL2_LIBRARY | cut -d= -f 2 | cut -d';' -f 1) "${{ github.workspace }}/platform-sdl/cmake-build/"
        if: ${{ startsWith(matrix.config.os, 'ubuntu-') }}
      - name: Pack macOS app bundle
        run: |
          ./.github/workflows/scripts/pack-macos-sdl.sh "${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl.app"
          rm -rf "${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl.app"
          mv "${{ github.workspace }}/platform-sdl/cmake-build/packed/fb_sdl.app" "${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl.app"
        if: ${{ startsWith(matrix.config.os, 'macos-') }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.artifact }}
          path: |
            ${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl
            ${{ github.workspace }}/platform-sdl/cmake-build/*.so
            ${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl.app/**

  build-sdl-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          Invoke-WebRequest 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip' -OutFile "${{ github.workspace }}\sdl2.zip"
          expand-archive -path "${{ github.workspace }}\sdl2.zip" -destinationpath "${{ github.workspace }}\sdl2"
        shell: powershell
      - name: Build with CMake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          cmakeGenerator: VS16Win64
          buildDirectory: "${{ github.workspace }}/platform-sdl/cmake-build"
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: -DCMAKE_BUILD_TYPE=Release -DSDL2_DIR="${{ github.workspace }}\sdl2\SDL2-2.0.12"
          buildWithCMakeArgs: "--config Release"
      - name: Copy SDL2 library
        run: Copy-Item -Path "${{ github.workspace }}\sdl2\SDL2-2.0.12\lib\x64\SDL2.dll" -Destination "${{ github.workspace }}/platform-sdl/cmake-build/Release/"
        shell: powershell
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: FunkyBoy-windows
          path: |
            ${{ github.workspace }}/platform-sdl/cmake-build/Release/fb_sdl.exe
            ${{ github.workspace }}/platform-sdl/cmake-build/Release/SDL2.dll
