name: Build 3DS platform

on:
  push:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'platform-3ds/**'
  pull_request:
    branches: [ master ]

jobs:
  build-3ds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run build in DevkitARM container
        uses: docker://devkitpro/devkitarm:20200730
        with:
          entrypoint: ./.github/workflows/scripts/build-in-docker.sh
          args: platform-3ds
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: FunkyBoy-3DS
          path: "${{ github.workspace }}/platform-3ds/cmake-build/fb_3ds.3dsx"
