name: Build SDL platform

on:
  push:
    # Temporary as long as I'm working on this branch
    # TODO: Just before creating a PR, put master here
    branches: [ graphics ]
  pull_request:
    branches: [ master ]

jobs:
  build-core:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
              - os: macos-latest
                generator: Ninja
              - os: windows-latest
                generator: VS16Win64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies (Ubuntu)
        if: ${{ startsWith(matrix.config.os, 'ubuntu-') }}
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Install dependencies (macOS)
        if: ${{ startsWith(matrix.config.os, 'macos-') }}
        run: brew install sdl2
      - name: run-cmake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          cmakeGenerator: ${{ matrix.config.generator }}
