name: Build SDL platform

on:
  push:
    # Temporary as long as I'm working on this branch
    # TODO: Just before creating a PR, just put master here
    branches: [ master, graphics ]
  pull_request:
    branches: [ master ]

jobs:
  build-sdl:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
              - os: macos-latest
                generator: Ninja
              - os: windows-latest
                generator: VS16Win64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies (Ubuntu)
        if: ${{ startsWith(matrix.config.os, 'ubuntu-') }}
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Install dependencies (macOS)
        if: ${{ startsWith(matrix.config.os, 'macos-') }}
        run: brew install sdl2
      - name: Install dependencies (Windows)
        if: ${{ startsWith(matrix.config.os, 'windows-') }}
        run: |
          Invoke-WebRequest 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip' -OutFile "${{ github.workspace }}\sdl2.zip"
          expand-archive -path "${{ github.workspace }}\sdl2.zip" -destinationpath "${{ github.workspace }}\sdl2"
        shell: powershell
      - name: Build with CMake (Linux & macOS)
        if: ${{ !startsWith(matrix.config.os, 'windows-') }}
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          cmakeGenerator: ${{ matrix.config.generator }}
          buildDirectory: "${{ github.workspace }}/platform-sdl/cmake-build"
      - name: Build with CMake (Windows)
        if: ${{ startsWith(matrix.config.os, 'windows-') }}
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/platform-sdl/CMakeLists.txt"
          cmakeGenerator: ${{ matrix.config.generator }}
          buildDirectory: "${{ github.workspace }}/platform-sdl/cmake-build"
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: -DSDL2_DIR="${{ github.workspace }}\sdl2\SDL2-2.0.12"
      - name: Upload artifact (Linux & macOS)
        if: ${{ !startsWith(matrix.config.os, 'windows-') }}
        uses: actions/upload-artifact@v2
        with:
          name: FunkyBoy
          path: "${{ github.workspace }}/platform-sdl/cmake-build/fb_sdl"
