name: Test

on:
  push:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
              - os: macos-latest
                generator: Ninja
              - os: windows-latest
                generator: VS16Win64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download Mooneye ROM tests (Windows)
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          Invoke-WebRequest 'https://gekkio.fi/files/mooneye-test-suite/mts-20211031-1956-1ae00bf/mts-20211031-1956-1ae00bf.zip' -OutFile "${{ github.workspace }}\mooneye.zip"
          expand-archive -path "${{ github.workspace }}\mooneye.zip" -destinationpath "${{ github.workspace }}\test\mooneye-test-roms-zip"
          Robocopy "${{ github.workspace }}\test\mooneye-test-roms-zip\mts-20211031-1956-1ae00bf" "${{ github.workspace }}\test\mooneye-test-roms" /E -ErrorAction SilentlyContinue
        shell: powershell
      - name: Download Mooneye ROM tests (Linux + macOS)
        if: ${{ matrix.config.os != 'windows-latest' }}
        run: |
          wget https://gekkio.fi/files/mooneye-test-suite/mts-20211031-1956-1ae00bf/mts-20211031-1956-1ae00bf.zip -O "${{ github.workspace }}/test/mooneye.zip"
          cd "${{ github.workspace }}/test" && unzip mooneye.zip && mv ./mts-20211031-1956-1ae00bf/** ./mooneye-test-roms/
      - name: run-cmake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeBuildType: Release
          cmakeListsTxtPath: "${{ github.workspace }}/test/CMakeLists.txt"
          buildDirectory: "${{ github.workspace }}/test/_fb_tests"
          cmakeGenerator: ${{ matrix.config.generator }}
      - name: Perform tests (Windows)
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: ".\\Release\\fb_tests.exe --mooneye"
        working-directory: "${{ github.workspace }}/test/_fb_tests"
      - name: Perform tests (Linux + macOS)
        if: ${{ matrix.config.os != 'windows-latest' }}
        run: "./fb_tests --mooneye"
        working-directory: "${{ github.workspace }}/test/_fb_tests"
