name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
              - os: macos-latest
                generator: Ninja
              - os: windows-latest
                generator: VS16Win64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: run-cmake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/test/CMakeLists.txt"
          buildDirectory: "${{ github.workspace }}/test/_fb_tests"
          cmakeGenerator: ${{ matrix.config.generator }}
      - name: Perform tests (Windows)
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: ".\\Debug\\fb_tests.exe"
        working-directory: "${{ github.workspace }}/test/_fb_tests"
      - name: Perform tests (Linux + macOS)
        if: ${{ matrix.config.os != 'windows-latest' }}
        run: "./fb_tests"
        working-directory: "${{ github.workspace }}/test/_fb_tests"
